name: guess_pokemon
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  ui_core:
    path: ../../features/ui_core
  dependencies:
    path: ../../dependencies
  domain:
    path: ../../domain
  flutter:
    sdk: flutter
  speech_to_text: ^5.4.3
  highlight_text: ^1.3.0

dev_dependencies:
  build_runner: 2.1.5
  fake_async: ^1.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_gen_runner: ^4.1.6
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/


flutter_gen:
  output: lib/assets/

scripts: ../../../derry.yaml