name: local
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dependencies:
    path: ../dependencies
  flutter:
    sdk: flutter
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1

dev_dependencies:
  build_runner: 2.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  objectbox_generator: ^1.4.1

flutter: