name: pokemon_quiz
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dependencies:
    path: modules/dependencies
  domain:
    path: modules/domain
  flutter:
    sdk: flutter
  pokedex:
    path: modules/features/pokedex
  guess_pokemon:
    path: modules/features/guess_pokemon
  pokemon_detail:
    path: modules/features/pokemon_detail
  setting:
    path: modules/features/setting
  ui_core:
    path: modules/features/ui_core

dev_dependencies:
  build_runner: 2.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

scripts: derry.yaml