name: network
description: A flutter module for networking
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.10
  firebase_remote_config: ^2.0.2
  dio: ^4.0.4
  dependencies:
    path: ../dependencies
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: 2.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  mocktail: ^0.3.0
  http_mock_adapter: ^0.3.2

flutter: